/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/g0xWJyIvtcE
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import Link from "next/link";
import { Button } from "@/components/ui/button";

export function NotesLayout() {
  return (
    <div className="flex h-screen">
      <aside className="w-64 bg-[#2C2C2E] p-6">
        <div className="flex items-center space-x-2 text-white mb-10">
          <LockOpenIcon className="h-6 w-6" />
          <span className="font-bold text-lg">NoteLock</span>
        </div>
        <nav className="space-y-2">
          <Link
            className="flex items-center space-x-2 text-white py-2 px-4 rounded-lg bg-[#3A3A3C]"
            href="#"
          >
            <HomeIcon className="h-5 w-5" />
            <span>Home</span>
          </Link>
          <Link
            className="flex items-center space-x-2 text-white py-2 px-4 rounded-lg hover:bg-[#3A3A3C] transition-colors"
            href="#"
          >
            <NotebookTextIcon className="h-5 w-5" />
            <span>Notes</span>
          </Link>
          <Link
            className="flex items-center space-x-2 text-white py-2 px-4 rounded-lg hover:bg-[#3A3A3C] transition-colors"
            href="#"
          >
            <KeyIcon className="h-5 w-5" />
            <span>Passwords</span>
          </Link>
          <Link
            className="flex items-center space-x-2 text-white py-2 px-4 rounded-lg hover:bg-[#3A3A3C] transition-colors"
            href="#"
          >
            <Heading6Icon className="h-5 w-5" />
            <span>Settings</span>
          </Link>
        </nav>
      </aside>
      <main className="flex-1 p-6">
        <header className="flex justify-between items-center mb-6">
          <h1 className="text-3xl font-bold">Untitled</h1>
          <MicroscopeIcon className="h-6 w-6 text-[#3A3A3C]" />
        </header>
        <section className="bg-white rounded-lg h-full" />
      </main>
      <div className="fixed bottom-4 right-4">
        <Button>Save</Button>
      </div>
    </div>
  );
}
